/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urlimagereader;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Admin_2
 */
public class ImageReader extends javax.swing.JFrame {

   
    /**
     * Creates new form ImageReader
     */
    public ImageReader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urltab = new javax.swing.JTextField();
        readtab = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        imagedisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urltab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urltabActionPerformed(evt);
            }
        });

        readtab.setText("read");
        readtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readtabActionPerformed(evt);
            }
        });

        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(urltab, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(readtab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(urltab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(readtab)
                .addGap(88, 88, 88)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagedisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urltabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urltabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urltabActionPerformed

    private void readtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readtabActionPerformed
          
      	//Image image = null;

        String url1=urltab.getText().toString().trim();        
 try {
            URL url = new URL(url1);
     BufferedImage image = ImageIO.read(url);
     Image dimg = image.getScaledInstance(imagedisplay.getWidth(), imagedisplay.getHeight(),Image.SCALE_SMOOTH);
     ImageIcon imageIcon = new ImageIcon(dimg);
         imagedisplay.setIcon(imageIcon); 


     
//     private static BufferedImage resizeImage(BufferedImage originalImage, int type,
//                                         Integer img_width, Integer img_height)
//{
//    BufferedImage resizedImage = new BufferedImage(img_width, img_height, type);
//    Graphics2D g = resizedImage.createGraphics();
//    g.drawImage(originalImage, 0, 0, img_width, img_height, null);
//    g.dispose();
//
//    return resizedImage;
 //}
     //  ImageIcon icon;
   //     icon = new ImageIcon(image);
//          BufferedImage bi = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_ARGB);
//         Graphics g = bi.createGraphics();
//      g.drawImage(image, 0, 0, WIDTH, HEIGHT, null);
//       ImageIcon icon= new ImageIcon(bi);
        // imagedisplay.setIcon(icon); 
          
     //     imagedisplay.setIcon(icon); 
        
//JLabel label = new JLabel(new ImageIcon(image));
//                    JFrame f = new JFrame();
//                    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                    f.getContentPane().add(label);
//                    f.pack();
//                    f.setLocation(200, 200);
//                    f.setVisible(true);
        } catch (IOException e) {
        	e.printStackTrace();
        }
 
  
 
 
        // TODO add your handling code here:
    }//GEN-LAST:event_readtabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel imagedisplay;
    private javax.swing.JButton readtab;
    private javax.swing.JTextField urltab;
    // End of variables declaration//GEN-END:variables
}
